### ISSUE TITLE
Open-source docker image availability

### ISSUE THREAD

**Issue by sarahhenkens** [appbaseio/reactivesearch-api#382]
When using the example include `docker-compose.yaml` file, it builds the API server locally and is able to boot up. When using the  dockerhub image available on https://hub.docker.com/r/appbaseio/reactivesearch-api, it fails to boot asking for a valid `APPBASE_ID`. 

Could this be happening because of the build args not being opensource? https://github.com/appbaseio/reactivesearch-api/blob/dev/Dockerfile#L3-L18

My modified docker-compose file:

```yaml
version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.2.0
    container_name: elasticsearch
    networks:
      - reactivesearch
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  reactivesearch:
    #build: ./
    image: appbaseio/reactivesearch-api:8.20.3
    environment:
      - ES_CLUSTER_URL=http://elasticsearch:9200
    container_name: reactivesearch
    env_file:
      - config/docker.env
    networks:
      - reactivesearch
    restart: on-failure
    ports:
      - 8000:8000
    depends_on:
      - elasticsearch

networks:
  reactivesearch:
    driver: bridge

```

```
sarah@remote-dev:~/reactivesearch-api$ docker compose up reactivesearch
[+] Running 1/1
 ✔ reactivesearch Pulled                                                                                       0.9s 
[+] Running 2/0
 ✔ Container elasticsearch   Running                                                                           0.0s 
 ✔ Container reactivesearch  Recreated                                                                         0.1s 
Attaching to reactivesearch
reactivesearch  | => port used 8000
reactivesearch  | [cmd] : reading env file .env . This may happen if the environments are declared directly :  open .env: no such file or directory
reactivesearch  | time="2024/01/09 19:08:35" level=fatal msg="APPBASE_ID env required but not present" file=" billing.go:615"
reactivesearch exited with code 0
```

### What version of `ReactiveSearch API` are you using ?

latest
